# Video
vo=gpu
# hwdec=vaapi
hwdec=auto-safe
# Default YouTube quality (IMPORTANT)
# profile=fast
ytdl-format=bestvideo[height<=?720][vcodec~='^(avc1|avc|h264)']+bestaudio/bestvideo[height<=?720][vcodec!*=av01]+bestaudio/best

# Cache
cache=yes
demuxer-max-bytes=100M
demuxer-readahead-secs=20

# Audio
ao=pulse,alsa

# UI
osd-level=1
save-position-on-quit=yes
