#!/bin/sh

# # Create a list of sinks with pretty names
# options=$(pactl -f json list sinks | jq -r '.[] | .description')
#
# # Let the user select a description
# selection=$(echo "$options" | dmenu -i -l 5 -c -p "Output:")
#
# # Extract the corresponding sink name
# sink_name=$(pactl -f json list sinks | jq -r --arg sink_pretty_name "$selection" '.[] | select(.description == $sink_pretty_name) | .name')
#
# # Set the selected sink as default
# if [ -n "$sink_name" ]; then
#     pactl set-default-sink "$sink_name" && notify-send "Audio switched to: $selection"
# else
#     notify-send "Audio switch failed"
# fi

SINK="alsa_output.pci-0000_00_1b.0.analog-stereo"

# Pretty names shown in dmenu
options="Speakers\nHeadphones"

# User selection
selection=$(printf "%b" "$options" | dmenu -i -l 5 -p "Output:")

case "$selection" in
    Speakers)
        pactl set-sink-port "$SINK" analog-output-speaker &&
            notify-send "Audio Output" "Speakers"
        ;;
    Headphones)
        pactl set-sink-port "$SINK" analog-output-headphones &&
            notify-send "Audio Output" "Headphones"
        ;;
    *)
        exit 0
        ;;
esac
